import Database from 'better-sqlite3'
import { buildStoredPricing } from '../lib/pricing'

function getTargetDbPath(): string {
  const url = process.env.DATABASE_URL
  if (!url?.startsWith('file:')) {
    throw new Error('DATABASE_URL must use the SQLite file: format')
  }
  return url.slice('file:'.length)
}

const db = new Database(getTargetDbPath())

const products = [
  {
    title: 'Écouteurs sans fil Bluetooth',
    description: 'Son stéréo haute qualité, autonomie 6h, compatible tous smartphones. Idéal pour les trajets quotidiens à Bamako.',
    price: 15900,
    currency: 'XOF',
    brand: 'SoundPro',
    category: 'electronique',
    categoryHierarchy: 'Électronique > Audio > Écouteurs',
    tags: JSON.stringify(['bluetooth', 'audio', 'sans-fil', 'écouteurs']),
    colors: JSON.stringify(['#222222', '#ffffff', '#e85d04']),
    materials: JSON.stringify(['Plastique ABS']),
    features: JSON.stringify(['Autonomie 6h', 'Compatible tous smartphones', 'Son stéréo haute qualité']),
    metaDescription: 'Écouteurs sans fil Bluetooth SoundPro - Son stéréo haute qualité, autonomie 6h. Livraison à Bamako.',
    slug: 'ecouteurs-sans-fil-bluetooth-soundpro',
    seoKeywords: JSON.stringify(['écouteurs bluetooth', 'sans fil', 'audio', 'bamako']),
    imageUrl: '/images/products/ecouteurs-sans-fil-bluetooth-soundpro.webp',
    isActive: true,
    confidence: 0.95,
  },
  {
    title: 'Chargeur rapide USB-C 65W',
    description: 'Charge ultra-rapide pour tous vos appareils. Compatible Samsung, Xiaomi, iPhone et plus.',
    price: 8500,
    currency: 'XOF',
    brand: 'ChargePlus',
    category: 'electronique',
    categoryHierarchy: 'Électronique > Accessoires > Chargeurs',
    tags: JSON.stringify(['chargeur', 'usb-c', 'rapide', '65w']),
    colors: JSON.stringify(['#ffffff', '#222222']),
    materials: JSON.stringify(['Plastique ignifuge']),
    features: JSON.stringify(['65W charge rapide', 'Compatible USB-C universel', 'Protection surtension']),
    metaDescription: 'Chargeur rapide USB-C 65W ChargePlus - Compatible Samsung, Xiaomi, iPhone. Livraison à Bamako.',
    slug: 'chargeur-rapide-usb-c-65w-chargeplus',
    seoKeywords: JSON.stringify(['chargeur usb-c', 'charge rapide', '65w', 'bamako']),
    imageUrl: '/images/products/chargeur-rapide-usb-c-65w-chargeplus.webp',
    isActive: true,
    confidence: 0.92,
  },
  {
    title: 'Montre connectée Sport',
    description: 'Suivi activité, fréquence cardiaque, notifications. Étanche 30m. Autonomie 7 jours.',
    price: 28500,
    currency: 'XOF',
    brand: 'TechTime',
    category: 'electronique',
    categoryHierarchy: 'Électronique > Montres > Connectées',
    tags: JSON.stringify(['montre', 'smartwatch', 'sport', 'connectée']),
    colors: JSON.stringify(['#222222', '#e85d04', '#1a936f']),
    materials: JSON.stringify(['Silicone', 'Aluminium']),
    features: JSON.stringify(['Suivi activité', 'Fréquence cardiaque', 'Étanche 30m', 'Autonomie 7 jours']),
    metaDescription: 'Montre connectée Sport TechTime - Suivi activité, fréquence cardiaque. Étanche 30m. Livraison Bamako.',
    slug: 'montre-connectee-sport-techtime',
    seoKeywords: JSON.stringify(['montre connectée', 'smartwatch', 'sport', 'bamako']),
    imageUrl: '/images/products/montre-connectee-sport-techtime.webp',
    isActive: true,
    confidence: 0.88,
  },
  {
    title: 'Powerbank 20000 mAh',
    description: "Ne tombez plus en panne de batterie. Charge 3 appareils simultanément. Idéal pour les coupures de courant.",
    price: 19900,
    currency: 'XOF',
    brand: 'PowerMax',
    category: 'electronique',
    categoryHierarchy: 'Électronique > Accessoires > Batteries',
    tags: JSON.stringify(['powerbank', 'batterie', 'portable', '20000mah']),
    colors: JSON.stringify(['#222222', '#1a936f']),
    materials: JSON.stringify(['Aluminium brossé']),
    features: JSON.stringify(['20000 mAh', 'Charge 3 appareils simultanément', 'Charge rapide 18W']),
    metaDescription: 'Powerbank 20000 mAh PowerMax - Charge 3 appareils. Idéal pour les coupures de courant à Bamako.',
    slug: 'powerbank-20000-mah-powermax',
    seoKeywords: JSON.stringify(['powerbank', 'batterie portable', '20000mah', 'bamako']),
    imageUrl: '/images/products/powerbank-20000-mah-powermax.webp',
    isActive: true,
    confidence: 0.97,
  },
  {
    title: 'Robe Bogolan moderne',
    description: "Fusion entre tradition malienne et coupe moderne. Disponible en tailles S à XL.",
    price: 12500,
    currency: 'XOF',
    brand: 'AfriStyle',
    category: 'mode',
    categoryHierarchy: 'Mode & Accessoires > Vêtements > Robes',
    tags: JSON.stringify(['robe', 'bogolan', 'africain', 'traditionnel', 'moderne']),
    colors: JSON.stringify(['#8B4513', '#1a1a2e']),
    materials: JSON.stringify(['Coton bogolan']),
    features: JSON.stringify(['Tailles S à XL', 'Tissu bogolan authentique', 'Coupe moderne']),
    metaDescription: 'Robe Bogolan moderne AfriStyle - Fusion tradition malienne et modernité. Livraison Bamako.',
    slug: 'robe-bogolan-moderne-afristyle',
    seoKeywords: JSON.stringify(['robe bogolan', 'mode africaine', 'mali', 'bamako']),
    imageUrl: '/images/products/robe-bogolan-moderne-afristyle.webp',
    isActive: true,
    confidence: 0.91,
  },
  {
    title: 'Sac à main cuir synthétique',
    description: 'Design élégant, compartiments multiples. Parfait pour le bureau ou les sorties.',
    price: 17500,
    currency: 'XOF',
    brand: 'LuxBag',
    category: 'mode',
    categoryHierarchy: 'Mode & Accessoires > Sacs > Sacs à main',
    tags: JSON.stringify(['sac', 'cuir', 'main', 'élégant']),
    colors: JSON.stringify(['#8B4513', '#222222', '#c9184a']),
    materials: JSON.stringify(['Cuir synthétique']),
    features: JSON.stringify(['Compartiments multiples', 'Fermeture éclair', 'Bandoulière amovible']),
    metaDescription: 'Sac à main cuir synthétique LuxBag - Design élégant, compartiments multiples. Livraison Bamako.',
    slug: 'sac-main-cuir-synthetique-luxbag',
    seoKeywords: JSON.stringify(['sac à main', 'cuir', 'mode', 'bamako']),
    imageUrl: '/images/products/sac-main-cuir-synthetique-luxbag.webp',
    isActive: true,
    confidence: 0.85,
  },
  {
    title: 'Sneakers casual unisexe',
    description: 'Légères et confortables pour toute la journée. Semelle antidérapante. Tailles 36-45.',
    price: 22000,
    currency: 'XOF',
    brand: 'UrbanStep',
    category: 'mode',
    categoryHierarchy: 'Mode & Accessoires > Chaussures > Sneakers',
    tags: JSON.stringify(['sneakers', 'chaussures', 'casual', 'unisexe']),
    colors: JSON.stringify(['#ffffff', '#222222', '#e85d04']),
    materials: JSON.stringify(['Mesh respirant']),
    features: JSON.stringify(['Tailles 36-45', 'Semelle antidérapante', 'Léger et confortable']),
    metaDescription: 'Sneakers casual unisexe UrbanStep - Légères et confortables. Tailles 36-45. Livraison Bamako.',
    slug: 'sneakers-casual-unisexe-urbanstep',
    seoKeywords: JSON.stringify(['sneakers', 'chaussures casual', 'unisexe', 'bamako']),
    imageUrl: '/images/products/sneakers-casual-unisexe-urbanstep.webp',
    isActive: true,
    confidence: 0.89,
  },
  {
    title: 'Ceinture en cuir tressé',
    description: 'Motif tressé élégant, boucle dorée. Convient à toutes les morphologies.',
    price: 6500,
    currency: 'XOF',
    brand: 'BeltCraft',
    category: 'mode',
    categoryHierarchy: 'Mode & Accessoires > Accessoires > Ceintures',
    tags: JSON.stringify(['ceinture', 'cuir', 'tressé', 'accessoire']),
    colors: JSON.stringify(['#8B4513', '#222222']),
    materials: JSON.stringify(['Cuir synthétique']),
    features: JSON.stringify(['Boucle dorée', 'Taille ajustable', 'Motif tressé']),
    metaDescription: 'Ceinture en cuir tressé BeltCraft - Motif élégant, boucle dorée. Livraison Bamako.',
    slug: 'ceinture-cuir-tresse-beltcraft',
    seoKeywords: JSON.stringify(['ceinture cuir', 'accessoire mode', 'bamako']),
    imageUrl: '/images/products/ceinture-cuir-tresse-beltcraft.webp',
    isActive: true,
    confidence: 0.82,
  },
  {
    title: 'Lampe LED rechargeable',
    description: "Indispensable pour les coupures de courant. 3 niveaux de luminosité, autonomie 8h.",
    price: 9800,
    currency: 'XOF',
    brand: 'LumiHome',
    category: 'maison',
    categoryHierarchy: 'Maison & Déco > Éclairage > Lampes LED',
    tags: JSON.stringify(['lampe', 'led', 'rechargeable', 'éclairage']),
    colors: JSON.stringify(['#ffffff', '#f5f5dc']),
    materials: JSON.stringify(['ABS', 'PC']),
    features: JSON.stringify(['3 niveaux luminosité', 'Autonomie 8h', 'Rechargeable USB']),
    metaDescription: 'Lampe LED rechargeable LumiHome - 3 niveaux de luminosité, autonomie 8h. Parfaite pour les coupures de courant. Livraison Bamako.',
    slug: 'lampe-led-rechargeable-lumihome',
    seoKeywords: JSON.stringify(['lampe led', 'rechargeable', 'coupure courant', 'bamako']),
    imageUrl: '/images/products/lampe-led-rechargeable-lumihome.webp',
    isActive: true,
    confidence: 0.98,
  },
  {
    title: 'Set de coussins décoratifs',
    description: 'Motifs africains modernes. Lot de 2 coussins 45×45cm. Lavables en machine.',
    price: 11500,
    currency: 'XOF',
    brand: 'DecoSoft',
    category: 'maison',
    categoryHierarchy: 'Maison & Déco > Textile > Coussins',
    tags: JSON.stringify(['coussin', 'décoratif', 'africain', 'textile']),
    colors: JSON.stringify(['#e85d04', '#1a1a2e', '#c9184a']),
    materials: JSON.stringify(['Coton imprimé']),
    features: JSON.stringify(['Lot de 2', '45×45cm', 'Lavable en machine', 'Motifs africains']),
    metaDescription: 'Set de coussins décoratifs DecoSoft - Motifs africains modernes. 45×45cm. Livraison Bamako.',
    slug: 'set-coussins-decoratifs-decosoft',
    seoKeywords: JSON.stringify(['coussins décoratifs', 'décoration africaine', 'bamako']),
    imageUrl: '/images/products/set-coussins-decoratifs-decosoft.webp',
    isActive: true,
    confidence: 0.84,
  },
  {
    title: 'Ventilateur portable USB',
    description: 'Compact et silencieux. Fonctionne sur batterie ou USB. 3 vitesses.',
    price: 7200,
    currency: 'XOF',
    brand: 'CoolBreeze',
    category: 'maison',
    categoryHierarchy: 'Maison & Déco > Climatisation > Ventilateurs',
    tags: JSON.stringify(['ventilateur', 'portable', 'usb', 'climatisation']),
    colors: JSON.stringify(['#ffffff', '#222222']),
    materials: JSON.stringify(['ABS']),
    features: JSON.stringify(['3 vitesses', 'Fonctionne sur USB ou batterie', 'Silencieux']),
    metaDescription: 'Ventilateur portable USB CoolBreeze - Compact, silencieux, 3 vitesses. Livraison Bamako.',
    slug: 'ventilateur-portable-usb-coolbreeze',
    seoKeywords: JSON.stringify(['ventilateur portable', 'usb', 'chaleur', 'bamako']),
    imageUrl: '/images/products/ventilateur-portable-usb-coolbreeze.webp',
    isActive: true,
    confidence: 0.90,
  },
  {
    title: 'Organisateur de bureau bambou',
    description: 'Rangez stylos, téléphone et accessoires avec style. Écologique et durable.',
    price: 13500,
    currency: 'XOF',
    brand: 'BambooDesk',
    category: 'maison',
    categoryHierarchy: 'Maison & Déco > Bureau > Organisateurs',
    tags: JSON.stringify(['bureau', 'organisateur', 'bambou', 'écologique']),
    colors: JSON.stringify(['#DEB887']),
    materials: JSON.stringify(['Bambou naturel']),
    features: JSON.stringify(['Écologique', 'Multiple compartiments', 'Durable']),
    metaDescription: 'Organisateur de bureau bambou BambooDesk - Écologique et élégant. Livraison Bamako.',
    slug: 'organisateur-bureau-bambou-bambodesk',
    seoKeywords: JSON.stringify(['organisateur bureau', 'bambou', 'écologique', 'bamako']),
    imageUrl: '/images/products/organisateur-bureau-bambou-bambodesk.webp',
    isActive: true,
    confidence: 0.86,
  },
  {
    title: 'Crème éclaircissante naturelle',
    description: 'À base de karité et vitamine C. Sans mercure ni corticoïdes. Résultat visible en 4 semaines.',
    price: 8900,
    currency: 'XOF',
    brand: 'NaturGlow',
    category: 'beaute',
    categoryHierarchy: 'Beauté & Soins > Soin visage > Crèmes',
    tags: JSON.stringify(['crème', 'éclaircissante', 'naturelle', 'karité', 'beauté']),
    colors: JSON.stringify(['#ffffff']),
    materials: JSON.stringify(['Formule naturelle']),
    features: JSON.stringify(['À base de karité', 'Vitamine C', 'Sans mercure', 'Sans corticoïdes']),
    metaDescription: 'Crème éclaircissante naturelle NaturGlow - Karité et vitamine C. Sans mercure. Livraison Bamako.',
    slug: 'creme-eclaircissante-naturelle-naturglow',
    seoKeywords: JSON.stringify(['crème éclaircissante', 'naturelle', 'karité', 'beauté bamako']),
    imageUrl: '/images/products/creme-eclaircissante-naturelle-naturglow.webp',
    isActive: true,
    confidence: 0.93,
  },
  {
    title: 'Huile de coco pure 500ml',
    description: 'Multiusage : cheveux, peau, cuisine. Pressée à froid, non raffinée. Origine Mali.',
    price: 5500,
    currency: 'XOF',
    brand: 'PureCocos',
    category: 'beaute',
    categoryHierarchy: 'Beauté & Soins > Soin corps > Huiles',
    tags: JSON.stringify(['huile', 'coco', 'naturelle', 'cheveux', 'peau']),
    colors: JSON.stringify(['#ffffff']),
    materials: JSON.stringify(['100% naturel']),
    features: JSON.stringify(['Pressée à froid', 'Non raffinée', 'Origine Mali', 'Multiusage']),
    metaDescription: 'Huile de coco pure 500ml PureCocos - Pressée à froid, origine Mali. Livraison Bamako.',
    slug: 'huile-coco-pure-500ml-purecocos',
    seoKeywords: JSON.stringify(['huile de coco', 'naturelle', 'cheveux', 'peau', 'bamako']),
    imageUrl: '/images/products/huile-coco-pure-500ml-purecocos.webp',
    isActive: true,
    confidence: 0.96,
  },
  {
    title: 'Palette maquillage 18 couleurs',
    description: 'Teintes adaptées aux carnations africaines. Facile à estomper, longue tenue 12h.',
    price: 14500,
    currency: 'XOF',
    brand: 'GlamPalette',
    category: 'beaute',
    categoryHierarchy: 'Beauté & Soins > Maquillage > Palettes',
    tags: JSON.stringify(['maquillage', 'palette', 'fard', 'beauté']),
    colors: JSON.stringify(['#c9184a', '#e85d04', '#1a1a2e']),
    materials: JSON.stringify(['Pigments longue tenue']),
    features: JSON.stringify(['18 couleurs', 'Longue tenue 12h', 'Adapté carnations africaines']),
    metaDescription: 'Palette maquillage 18 couleurs GlamPalette - Teintes pour carnations africaines, 12h tenue. Livraison Bamako.',
    slug: 'palette-maquillage-18-couleurs-glampalette',
    seoKeywords: JSON.stringify(['palette maquillage', 'beauté', 'africaine', 'bamako']),
    imageUrl: '/images/products/palette-maquillage-18-couleurs-glampalette.webp',
    isActive: true,
    confidence: 0.87,
  },
  {
    title: 'Fil électrique multiprise 5m',
    description: 'Norme CE, protection contre les surtensions. 4 prises + 2 USB. Câble 5 mètres.',
    price: 6800,
    currency: 'XOF',
    brand: 'SafePower',
    category: 'divers',
    categoryHierarchy: 'Divers > Électricité > Multiprises',
    tags: JSON.stringify(['multiprise', 'électrique', 'usb', 'sécurité']),
    colors: JSON.stringify(['#ffffff', '#222222']),
    materials: JSON.stringify(['Cuivre', 'PVC ignifuge']),
    features: JSON.stringify(['4 prises + 2 USB', 'Câble 5m', 'Protection surtension', 'Norme CE']),
    metaDescription: 'Multiprise 5m SafePower - 4 prises + 2 USB, protection surtension. Livraison Bamako.',
    slug: 'multiprise-5m-safepower',
    seoKeywords: JSON.stringify(['multiprise', 'fil électrique', 'usb', 'bamako']),
    imageUrl: '/images/products/multiprise-5m-safepower.webp',
    isActive: true,
    confidence: 0.94,
  },
  {
    title: 'Sac à dos étanche 30L',
    description: "Compartiment laptop 15\", nombreuses poches. Idéal pour l'école et le travail.",
    price: 18500,
    currency: 'XOF',
    brand: 'TrekPack',
    category: 'divers',
    categoryHierarchy: 'Divers > Bagagerie > Sacs à dos',
    tags: JSON.stringify(['sac à dos', 'étanche', 'laptop', 'école']),
    colors: JSON.stringify(['#222222', '#1a936f', '#e85d04']),
    materials: JSON.stringify(['Nylon 420D']),
    features: JSON.stringify(['30L', 'Compartiment laptop 15"', 'Étanche', 'Nombreuses poches']),
    metaDescription: 'Sac à dos étanche 30L TrekPack - Compartiment laptop 15". Livraison Bamako.',
    slug: 'sac-dos-etanche-30l-trekpack',
    seoKeywords: JSON.stringify(['sac à dos', 'étanche', 'laptop', 'bamako']),
    imageUrl: '/images/products/sac-dos-etanche-30l-trekpack.webp',
    isActive: true,
    confidence: 0.91,
  },
  {
    title: 'Calculatrice scientifique',
    description: 'Fonctions avancées pour lycée et université. Affichage 2 lignes, 240 fonctions.',
    price: 9500,
    currency: 'XOF',
    brand: 'MathPro',
    category: 'divers',
    categoryHierarchy: 'Divers > Fournitures > Calculatrices',
    tags: JSON.stringify(['calculatrice', 'scientifique', 'lycée', 'université']),
    colors: JSON.stringify(['#222222', '#1a936f']),
    materials: JSON.stringify(['ABS']),
    features: JSON.stringify(['240 fonctions', 'Affichage 2 lignes', 'Pour lycée et université']),
    metaDescription: 'Calculatrice scientifique MathPro - 240 fonctions, affichage 2 lignes. Livraison Bamako.',
    slug: 'calculatrice-scientifique-mathpro',
    seoKeywords: JSON.stringify(['calculatrice scientifique', 'lycée', 'université', 'bamako']),
    imageUrl: '/images/products/calculatrice-scientifique-mathpro.webp',
    isActive: true,
    confidence: 0.88,
  },
]

async function main() {
  console.log('🌱 Seeding database...')

  let created = 0
  let updated = 0

  for (const product of products) {
    const data = {
      ...product,
      ...buildStoredPricing(product.price),
    }
    const existing = db.prepare(`SELECT id FROM "Product" WHERE "slug" = ?`).get(product.slug) as { id: number } | undefined
    if (existing) {
      db.prepare(`
        UPDATE "Product"
        SET "title" = ?, "description" = ?, "basePrice" = ?, "price" = ?, "currency" = ?, "brand" = ?,
            "category" = ?, "categoryHierarchy" = ?, "tags" = ?, "colors" = ?, "materials" = ?, "features" = ?,
            "metaDescription" = ?, "slug" = ?, "seoKeywords" = ?, "imageUrl" = ?, "isActive" = ?, "confidence" = ?,
            "updatedAt" = CURRENT_TIMESTAMP
        WHERE "slug" = ?
      `).run(
        data.title, data.description, data.basePrice, data.price, data.currency, data.brand,
        data.category, data.categoryHierarchy, data.tags, data.colors, data.materials, data.features,
        data.metaDescription, data.slug, data.seoKeywords, data.imageUrl, data.isActive ? 1 : 0, data.confidence,
        product.slug
      )
      updated++
    } else {
      db.prepare(`
        INSERT INTO "Product" (
          "title", "description", "basePrice", "price", "currency", "brand", "category", "categoryHierarchy",
          "tags", "colors", "materials", "features", "metaDescription", "slug", "seoKeywords", "imageUrl",
          "isActive", "confidence", "createdAt", "updatedAt"
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
      `).run(
        data.title, data.description, data.basePrice, data.price, data.currency, data.brand,
        data.category, data.categoryHierarchy, data.tags, data.colors, data.materials, data.features,
        data.metaDescription, data.slug, data.seoKeywords, data.imageUrl, data.isActive ? 1 : 0, data.confidence
      )
      created++
    }
  }

  console.log(`✅ Done: ${created} created, ${updated} updated`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => db.close())
